exports.run = async (bot, message, args) => {
    message.channel.send({embed: {
        color: 3447003,
        author: {
          name: bot.user.username,
          icon_url: bot.user.avatarURL
        },
        title: "La Cosa Nostra Till I Die.",
        description: "I'm not in the mood for the toys, or games, or kidding. I'm not in the mood for clans. I'm not in the mood for gangs. I'm not in the mood for none of that stuff there. This is gonna be La Cosa Nostra 'til I die. Be it an hour from now, or be it tonight, or a hundred years from now when I'm in jail. It's gonna be La Cosa Nostra. This ain't gonna be a bunch of your friends, they're gonna be friends of ours. It's gonna be the way I say it's gonna be, La Cosa Nostra. A Cosa Nostra. You might say, because a guy's nice to you, and I'm not talking about you, I'm just sayin' you might think it makes him a good guy. It makes him a motherfucker to me. It don't make him a good guy. It makes him a good guy if he's one of us and he proves he's part of us. And I'm the best judge of that, I think, right now. So you got a reason Lorenzo, say it. I love you, say it, but that's not the point. This thing here, I'm not so sure of the five guys that I'm puttin' in are the first five guys that should be going in. What can you do? I'm doing it because I want this thing to be proper. We got some guys that can preserve it and they'll be there forever. They won't be having secret fuckin' parties where people won't be allowed. That we don't want and that we don't need, that's for sure. I wanna see an effort. I gotta see an effort for a Cosa Nostra. How many of these guys come, come tell me I feel sorry you got trouble. I don't, I don't need that. I ain't got no trouble, I ain't got no trouble at all. I'm gonna be all right. They the ones who got the fuckin' trouble. And I don't mean the cops, I mean the people. The people who coulda made this a joke, you know what I mean. That's not a fuckin' joke guys. Even, even, even some guys, some people downstairs now who I know whose fucking stomach is rotten. I know whose stomach ain't rotten. I could smell it the way a dog senses when a guy's got fear."
      }
    });
}